# || Numpy ||

Instalando as dependências

In [ ]:
!pip install numpy


Importando a biblioteca Numpy

In [ ]:
import numpy as np


Criando uma Array Numpy

In [ ]:
data = np.array([2, 4, 6, 8, 10])

print(data)
print(type(data))
print(data.shape)


[ 2  4  6  8 10]
<class 'numpy.ndarray'>
(5,)


Criando automaticamente uma Array Numpy com dados ordenados

In [ ]:
data = np.arange(15)

print(data)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Criando automaticamente uma Array Numpy com dados aleatórios (float entre 0 e 1)

In [ ]:
data = np.random.rand(15)

print(data)


[0.46767506 0.33941593 0.24069971 0.14360643 0.69268799 0.98486848
 0.13006424 0.27738541 0.90083945 0.69435152 0.00873169 0.238581
 0.80114636 0.94970789 0.37813807]


Criando uma Array Numpy com dados aleatórios (int entre 0 e o valor definido)

In [ ]:
data = np.random.randint(10, size = 10)
# números de 0 a 10, size define quantos elementos serão gerados

print(data)


[5 9 3 3 0 6 9 1 6 3]


Criando uma Array Numpy com dados aleatórios (float entre 0 e 1)

In [ ]:
data = np.random.random((2, 2))

print(data)


[[0.3105231  0.46127506]
 [0.25691878 0.31584648]]


Criando uma Array Numpy de zeros

In [ ]:
data = np.zeros((3, 4))
# 3 linhas e 4 colunas

print(data)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


O mesmo também pode ser feito com números 1

In [ ]:
data = np.ones((3, 4))
# 3 linhas e 4 colunas

print(data)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Criando uma Array Numpy com valores vazios (em notação científica, significando ser menor que 0)

In [ ]:
data = np.empty((3, 4))

print(data)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2.85964880e-316 2.88902396e-316 3.95252517e-323 2.88902396e-316]
 [3.95252517e-323 2.88902396e-316 2.79437377e+276 0.00000000e+000]
 [2.88904926e-316 2.88904926e-316 2.88904926e-316 0.00000000e+000]]


Criando uma Array Numpy de números negativos

In [ ]:
data = np.arange(10) * -1

print(data)


[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


Criando uma Array Numpy unidimensional

In [ ]:
data = np.random.randint(5, size = 10)
# números de 0 a 5, size define quantos elementos serão gerados

print(data)
print(data.shape)


[4 4 1 2 3 3 1 2 3 0]
(10,)


Criando uma Array Numpy bidimensional

In [ ]:
data2 = np.random.randint(5, size = (3, 4))
# números de 0 a 5, distribuidos em 3 linhas e 4 colunas

print(data2)
print(data2.shape)


[[2 0 3 2]
 [0 4 2 1]
 [3 0 1 0]]
(3, 4)


Criando uma Array Numpy tridimensional

In [ ]:
data3 = np.random.randint(5, size = (5, 3, 4))
# números de 0 a 5, 5 camadas cada uma com 3 linhas e 4 colunas

print(data3)
print(data3.shape)


[[[0 2 4 4]
  [0 1 1 2]
  [1 2 2 0]]

 [[1 4 4 3]
  [0 4 3 3]
  [1 1 2 4]]

 [[2 1 1 2]
  [1 1 3 2]
  [3 0 2 4]]

 [[2 4 1 3]
  [0 0 3 4]
  [0 4 3 0]]

 [[2 2 3 3]
  [1 4 4 3]
  [2 0 3 3]]]
(5, 3, 4)


Convertendo uma array multidimensional para unidimensional

In [ ]:
data4 = np.array([(1,2,3,4),(3,1,4,2)])

print(data4)

data4_flat = data4.flatten()

print(data4_flat)


[[1 2 3 4]
 [3 1 4 2]]
[1 2 3 4 3 1 4 2]


Criando manualmente uma Array a partir de listas

In [ ]:
data4 = np.array([[1, 2, 3, 4], [1, 3, 5, 7]])

print(data4)


[[1 2 3 4]
 [1 3 5 7]]


Verificando o tipo de dado

In [ ]:
print(type(data3))
print(data3.dtype)


<class 'numpy.ndarray'>
int64


Verificando o tamanho da matriz

In [ ]:
data3 = np.random.randint(5, size = (5, 3, 4))

print(data3.ndim)
# número de dimensões

print(data3.shape)
# formato de cada dimensão

print(data3.size)
# tamanho total da matriz


3
(5, 3, 4)
60


Verificando o tamanho em bytes de cada item e de toda a matriz

In [ ]:
print(f'Cada elemento possui {data3.itemsize} bytes')
print(f'Toda a matriz possui {data3.nbytes} bytes')


Cada elemento possui 8 bytes
Toda a matriz possui 480 bytes


Consultando o elemento de maior valor da Array

In [ ]:
data = np.arange(15)

print(data)
print(data.max())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
14


Consultando um dado/valor de um elemento através de seu índice (unidimensional)

In [ ]:
data = np.arange(15)

print(data)
print(data[8])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
8


In [ ]:
data

print(data)
print(data[-5])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
10


Consultando um dado/valor de um elemento através de seu índice (multidimensional)

In [ ]:
data2 = np.random.randint(5, size = (3, 4))

print(data2)
print(data2[0, 2])
# linha 0, coluna 2 (lembrando que o índice para coluna também começa em 0, 0-1-2-3)


[[2 3 2 0]
 [0 3 0 1]
 [3 1 4 3]]
2


Consultando um intervalo de elementos

In [ ]:
data

print(data)

print(data[:5])
# apenas os 5 primeiros

print(data[3:])
# do terceiro elemento em diante (elemento, e não índice)

print(data[4:8])
# do quarto elemento até o oitavo (4º, 5º, 6º 7º e 8º elemento)

print(data[::2])
# de dois em dois elementos

print(data[3::])
# pula os 3 primeiros elementos e imprime o resto


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[0 1 2 3 4]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[4 5 6 7]
[ 0  2  4  6  8 10 12 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]


Modificando dados/valores manualmente por meio de seu índice

In [ ]:
data2

print(data2)

data2[0, 0] = 10
# elemento situado na posição 0x0 do índice passará a ter o valor atribuído 10

print(data2)


[[2 3 2 0]
 [0 3 0 1]
 [3 1 4 3]]
[[10  3  2  0]
 [ 0  3  0  1]
 [ 3  1  4  3]]


Inserindo números diferentes de INT, os mesmos serão convertidos para INT para que não haja erros

In [ ]:
data2

data2[1, 1] = 6.82945

print(data2)


[[10  3  2  0]
 [ 0  6  0  1]
 [ 3  1  4  3]]


Definindo manualmente o tipo de dado em uma Array

In [ ]:
data2 = np.array([8, -3, 5, 9], dtype = 'float')

print(data2)
print(type(data2[0]))


[ 8. -3.  5.  9.]
<class 'numpy.float64'>


Criando uma Array Numpy onde os intervalos dos números são igualmente distribuídos

In [ ]:
data = np.linspace(0, 1, 7)
# 7 números, gerados de 0 a 1, com intervalo igual entre cada número gerado

print(data)


[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


Criando uma Array Numpy com formato definido manualmente

In [ ]:
data5 = np.arange(8)

print(data5)

data5 = data5.reshape(2, 4)
# a multiplicação dessas dimensões deve ser o número de elementos. ex 2 x 4 = 8

print(data5)


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


Criando uma Array Numpy com números aleatórios, de tamanho predefinido em variável

In [ ]:
tamanho = 10

data6 = np.random.permutation(tamanho)

print(data6)


[1 8 7 4 5 6 2 3 0 9]


Aplicando operador lógico sobre uma Array Numpy

In [ ]:
data7 = np.arange(10)

print(data7)
print(data7 > 3)


[0 1 2 3 4 5 6 7 8 9]
[False False False False  True  True  True  True  True  True]


In [ ]:
data7 = np.arange(10)

print(data7)
print(data7[4] > 5)


[0 1 2 3 4 5 6 7 8 9]
False


Aplicando operador aritmético sobre uma Array Numpy

In [ ]:
data8 = [1, 2, 3, 4, 5, 6, 7, 8]
print(data8)


data8 = np.array(data8)
# após convertido para array o operador + sempre fará a soma

print(data8 + 10)


[1, 2, 3, 4, 5, 6, 7, 8]
[11 12 13 14 15 16 17 18]


Criando uma matriz diagonal

In [ ]:
data9 = np.diag((1, 2, 3, 4, 5, 6, 7, 8))

print(data9)


[[1 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 5 0 0 0]
 [0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 8]]


In [ ]:
# algo parecido pode ser feito com a função np.eye( )

data9 = np.eye(4)

print(data9)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Criando padrões duplicados

In [ ]:
data10 = np.tile(np.array([[9, 4], [3, 7]]), 4)
# 9, 4, elementos da primeira linha, 3, 7 da segunda, duplicados 4 vezes na mesma linha

print(data10)


[[9 4 9 4 9 4 9 4]
 [3 7 3 7 3 7 3 7]]


In [ ]:
data10 = np.tile(np.array([[9, 4], [3, 7]]), (2,2))
# mesmo exemplo que o anterior, mas duplicados linha e coluna

print(data10)


[[9 4 9 4]
 [3 7 3 7]
 [9 4 9 4]
 [3 7 3 7]]


Somando um valor a cada elemento da Array

In [ ]:
data11 = np.arange(0, 15)

print(data11)

data11 = np.arange(0, 15) + 1

print(data11)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
data11 = np.arange(0, 30,3) + 3
# somando 3 ao valor de cada elemento, de 3 em 3 elementos

print(data11)


[ 3  6  9 12 15 18 21 24 27 30]


Realizando soma de Arrays

In [ ]:
d1 = np.array([ 3,  6,  9, 12, 15])
d2 = np.array([ 1,  2,  3,  4,  5])

d3 = d1 + d2

print(d3)


[ 4  8 12 16 20]


Subtração de Arrays

In [ ]:
d1 = np.array([ 3,  6,  9, 12, 15])
d2 = np.array([ 1,  2,  3,  4,  5])

d3 = d1 - d2

print(d3)


[ 2  4  6  8 10]


Divisão de Arrays

In [ ]:
d1 = np.array([ 3,  6,  9, 12, 15])
d2 = np.array([ 1,  2,  3,  4,  5])

d3 = d1 / d2

print(d3)


[3. 3. 3. 3. 3.]


Multiplicação de Arrays

In [ ]:
d1 = np.array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])
d2 = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

d3 = d1 * d2

print(d3)


[  3  12  27  48  75 108 147 192 243 300]


Operações Lógicas com Arrays

In [ ]:
d1 = np.array([ 3,  6,  9, 12, 15, 18, 21])
d2 = np.array([ 1,  2,  3,  4,  5, 20, 25])

d3 = d2 > d1

print(d3)


[False False False False False  True  True]


Matriz transposta  / Transformando linhas em colunas e vice versa de forma proporcional

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1)
print(arr1.shape)

arr1_transposta = arr1.transpose()

print(arr1_transposta)
print(arr1_transposta.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


Salvando uma Array no disco local

In [ ]:
data = np.array([ 3,  6,  9, 12, 15])

np.save('minha_array', data)


Carregando uma Array do disco local

In [ ]:
np.load('minha_array.npy')


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

## Vetores não ordenados

In [ ]:
import numpy as np

class Vetor:
    def __init__(self, tamanho):
        self.tamanho = tamanho
        self.ultimo = -1
        self.elementos = np.empty(self.tamanho, dtype = int)

    def exibe_em_tela(self):
        if self.ultimo == -1:
            print('Vetor vazio!!!')
        else:
            for i in range(self.ultimo + 1):
                print(i, self.elementos[i])
    
    def insere_elemento(self, elemento):
        if self.ultimo == self.tamanho -1:
            print('Capacidade máxima atingida')
        else:
            self.ultimo += 1
            self.elementos[self.ultimo] = elemento
    
    def pesquisa_elemento(self, elemento):
        for i in range(self.ultimo + 1):
            if elemento == self.elementos[i]:
                return i
        return -1
    
    def exclui_elemento(self, elemento):
        posicao = self.pesquisa_elemento(elemento)
        if posicao == -1:
            return -1
        else:
            for i in range(posicao, self.ultimo):
                self.elementos[i] = self.elementos[i + 1]
            self.ultimo -= 1


In [ ]:
base = Vetor(10)
base.exibe_em_tela()
# Retornará 'Vetor vazio' pois até esse momento não foram inseridos dados no vetor


Vetor vazio!!!


In [ ]:
base.insere_elemento(9)
base.insere_elemento(3)
base.exibe_em_tela()
# Retornará índice 0 9 e índice 1 3


0 9
1 3


In [ ]:
print(base.pesquisa_elemento(9))
# Retorna o número de índice onde está situado o elemento 9


0


In [ ]:
print(base.ultimo)
# Retornará o último valor de índice, para implicitamente descobrirmos qual o tamanho do vetor


1


In [ ]:
base.insere_elemento(1)
base.insere_elemento(4)
base.insere_elemento(5)
base.insere_elemento(12)
base.insere_elemento(20)
base.exibe_em_tela()


0 9
1 3
2 1
3 4
4 5
5 12
6 20


In [ ]:
base.exclui_elemento(12)
# Exclui o elemento em questão, realocando seu número de índice para outro elemento
base.exibe_em_tela()


0 9
1 3
2 1
3 4
4 5
5 20


## Vetores Ordenados

In [ ]:
import numpy as np

class Vetor:

    def __init__(self, tamanho):
        self.tamanho = tamanho
        self.ultimo = -1
        self.elementos = np.empty(self.tamanho, dtype=int)

    def exibe_em_tela(self):
        if self.ultimo == -1:
            print('Vetor atualmente vazio...')
        else:
            for i in range(self.ultimo + 1):
                print(i, ' - ', self.elementos[i])

    def insere_elemento(self, valor):
        if self.ultimo == self.tamanho - 1:
            print('Capacidade máxima atingida')
            return

        posicao = 0
        for i in range(self.ultimo + 1):
            posicao = i
            if self.elementos[i] > valor:
                break
            if i == self.ultimo:
                posicao = i + 1

        x = self.ultimo
        while x >= posicao:
            self.elementos[x + 1] = self.elementos[x]
            x -= 1

        self.elementos[posicao] = valor
        self.ultimo += 1

    def pesquisa_linear(self, valor):
        for i in range(self.ultimo + 1):
            if self.elementos[i] > valor:
                return -1
            if self.elementos[i] == valor:
                return i
            if i == self.ultimo:
                return -1

    def pesquisa_binaria(self, valor):
        limite_inferior = 0
        limite_superior = self.ultimo

        while True:
            posicao_atual = int((limite_inferior + limite_superior) / 2)
            if self.elementos[posicao_atual] == valor:
                return posicao_atual
            elif limite_inferior > limite_superior:
                return -1
            else:
                if self.elementos[posicao_atual] < valor:
                    limite_inferior = posicao_atual + 1
                else:
                    limite_superior = posicao_atual - 1

    def pesquisa_elemento(self, elemento):
        for i in range(self.ultimo + 1):
            if elemento == self.elementos[i]:
                return i
        return -1

    def exclui_elemento(self, valor):
        posicao = self.pesquisa_elemento(valor)
        if posicao == -1:
            return -1
        else:
            for i in range(posicao, self.ultimo):
                self.elementos[i] = self.elementos[i + 1]

            self.ultimo -= 1


In [ ]:
base = Vetor(10)
base.exibe_em_tela()
# Retornará 'Vetor atualmente vazio...' pois até esse momento não foram inseridos dados no vetor


Vetor atualmente vazio...


In [ ]:
# Nesse caso, por se tratar de um vetor ordenado, os elementos serão adicionados
# de modo que ficarão classificados por padrão em ordem crescente, sempre que um
# novo elemento for inserido, respeitará essa ordem crescente e ocupará sua devida
# posição

base.insere_elemento(1)
base.insere_elemento(44)
base.insere_elemento(5)
base.insere_elemento(12)
base.insere_elemento(20)
base.insere_elemento(21)
base.exibe_em_tela()


0  -  1
1  -  5
2  -  12
3  -  20
4  -  21
5  -  44


In [ ]:
print(base.ultimo)
# Retornará o último valor de índice, para implicitamente descobrirmos qual o tamanho do vetor


5


In [ ]:
base.pesquisa_elemento(20)
base.pesquisa_binaria(20)
base.pesquisa_linear(20)

# Retornará -1 quando um elemento não estiver presente no vetor


2

In [ ]:
base.exclui_elemento(12)
# Exclui o elemento em questão, realocando seu número de índice para outro elemento
base.exibe_em_tela()


0  -  1
1  -  5
2  -  20
3  -  21
4  -  44
